### ISSUE TITLE
Incorrect system url in allergyType.properties

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/Impfmodul-Phase-I#11]
In the config file [allergyType.properties](Implementation/vaccination-module-backend/config/valuelists/allergyType.properties) the definition of a code is not correct.
Should be &lt;code&gt;,<display&gt;,&lt;codesystem url&gt;

but the codesystem url is an html website of the valueset.

**Comment by pjolo** [comment]
@msmock  This is not used in the vaccination module

**Comment by ch-fuchs** [comment]
This is not exactly true. While it is not possible for the user to choose a value anymore, we are using a default value to correspond to the FHIR standard, nevertheless, value list has been updated to correspond to the system url
http://hl7.org/fhir/allergy-intolerance-type
as described in
http://hl7.org/fhir/R5/valueset-allergy-intolerance-type.html
