### ISSUE TITLE
Incorrect system url in allergyVerificationStatus.properties

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/Impfmodul-Phase-I#12]
In the config file [allergyVerificationStatus.properties](Implementation/vaccination-module-backend/config/valuelists/allergyVerificationStatus.properties) the definition of a code is not correct.
Should be &lt;code&gt;,<display&gt;,&lt;codesystem url&gt;

but the codesystem url is an html website of the valueset.

**Comment by pjolo** [comment]
@ralych  I have made an export from the vaccination module. In my view, targetDeseases is correctly specified. 
See the picture below:



![image](https://github.com/ehealthsuisse/Impfmodul-Phase-I/assets/87263053/855f98d1-c12f-4948-a5a9-4195497482fe)





Can you tell us what exactly is wrong?

**Comment by ch-fuchs** [comment]
Value list has been updated to correspond to the system url
http://terminology.hl7.org/CodeSystem/allergyintolerance-verification
as described in
http://hl7.org/fhir/R5/valueset-allergyintolerance-verification.html
