### ISSUE TITLE
Incorrect system url in conditionClinicalStatus.properties

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/Impfmodul-Phase-I#13]
In the config file [conditionClinicalStatus.properties](Implementation/vaccination-module-backend/config/valuelists/conditionClinicalStatus.properties) the definition of a code is not correct.
Should be &lt;code&gt;,<display&gt;,&lt;codesystem url&gt;

but the codesystem url is an html website of the valueset.

**Comment by ch-fuchs** [comment]
Value list has been updated to correspond to the system url
http://terminology.hl7.org/CodeSystem/condition-clinical
as described in
http://hl7.org/fhir/R5/valueset-condition-clinical.html
