### ISSUE TITLE
Incorrect system url in conditionSeverity.properties

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/Impfmodul-Phase-I#16]
In the config file [conditionSeverity.properties](Implementation/vaccination-module-backend/config/valuelists/conditionSeverity.properties) the definition of a code is not correct.
Should be &lt;code&gt;,<display&gt;,&lt;codesystem url&gt;

but the codesystem url is an html website of the valueset.

**Comment by ch-fuchs** [comment]
This is not completely true, although the user is no longer able to choose a value, we are still setting a default value to correspond to a standard, nevertheless, value list has been updated to correspond to the system url
http://snomed.info/sct
as described in 
http://hl7.org/fhir/R5/valueset-condition-severity.html
