### ISSUE TITLE
Incorrect system url in conditionVerificationStatus.properties

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/Impfmodul-Phase-I#17]
In the config file [conditionVerificationStatus.properties](Implementation/vaccination-module-backend/config/valuelists/conditionVerificationStatus.properties) the definition of a code is not correct.
Should be &lt;code&gt;,<display&gt;,&lt;codesystem url&gt;

but the codesystem url is an html website of the valueset.

**Comment by pjolo** [comment]
@ralych  I have made an export from the vaccination module. In my view, targetDeseases is correctly specified. 
See the picture below:


![image](https://github.com/ehealthsuisse/Impfmodul-Phase-I/assets/87263053/8374ce21-5d0c-4fc0-af6c-261b51321893)




Can you tell us what exactly is wrong?

**Comment by ch-fuchs** [comment]
Value list has been updated to correspond to the system
http://terminology.hl7.org/CodeSystem/condition-ver-status
as described in 
http://hl7.org/fhir/R5/valueset-condition-ver-status.html
