### ISSUE TITLE
Incorrect system url in confidentialityCode.properties

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/Impfmodul-Phase-I#18]
In the config file [confidentialityCode.properties](Implementation/vaccination-module-backend/config/valuelists/confidentialityCode.properties) the definition of a code is not correct.
Should be &lt;code&gt;,<display&gt;,&lt;codesystem url&gt;

but the codesystem url is an html website of the valueset.

**Comment by pjolo** [comment]
@ralych  I have made an export from the vaccination module. In my view, targetDeseases is correctly specified. 
See the picture below:


![image](https://github.com/ehealthsuisse/Impfmodul-Phase-I/assets/87263053/34f15155-3190-4846-b9dd-1b7d9f92326b)




Can you tell us what exactly is wrong?

**Comment by ch-fuchs** [comment]
Confidentiality code value list was updated and corresponds to the specification of

https://www.fedlex.admin.ch/filestore/fedlex.data.admin.ch/eli/oce/2023/51/de/pdf-a/fedlex-data-admin-ch-eli-oce-2023-51-de-pdf-a.pdf
