### ISSUE TITLE
Incorrect system url in immunizationReasonCode.properties

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/Impfmodul-Phase-I#19]
In the config file [immunizationReasonCode.properties](Implementation/vaccination-module-backend/config/valuelists/immunizationReasonCode.properties) the definition of a code is not correct.
Should be &lt;code&gt;,<display&gt;,&lt;codesystem url&gt;

but the codesystem url is an html website of the valueset.

**Comment by pjolo** [comment]
@ralych  I have made an export from the vaccination module. In my view, targetDeseases is correctly specified. 
See the picture below:


![image](https://github.com/ehealthsuisse/Impfmodul-Phase-I/assets/87263053/ffceecaf-fd8a-4aab-b0c6-40c32acaa7eb)




Can you tell us what exactly is wrong?

**Comment by ch-fuchs** [comment]
Fehler wurde mit Version 1.3 korrigiert.
Neue systemurl ist nun: http://snomed.info/sct
