### ISSUE TITLE
Incorrect system url in immunizationStatusCode.properties

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/Impfmodul-Phase-I#20]
In the config file [immunizationStatusCode.properties](Implementation/vaccination-module-backend/config/valuelists/immunizationStatusCode.properties) the definition of a code is not correct.
Should be &lt;code&gt;,<display&gt;,&lt;codesystem url&gt;

but the codesystem url is an html website of the valueset.

**Comment by pjolo** [comment]
@ralych I have made an export from the vaccination module. In my view, targetDeseases is correctly specified. 
See the picture below:



![image](https://github.com/ehealthsuisse/Impfmodul-Phase-I/assets/87263053/4e7573a5-99f0-4b66-a82e-2e78ad55214d)


Can you tell us what exactly is wrong?

**Comment by ch-fuchs** [comment]
Fehler wurde mit Version 1.3 korrigiert.
Neue systemurl ist nun: http://hl7.org/fhir/event-status
