### ISSUE TITLE
Incorrect system url in immunizationTargetDesease.properties

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/Impfmodul-Phase-I#21]
In the config file [immunizationTargetDesease.properties](Implementation/vaccination-module-backend/config/valuelists/immunizationTargetDesease.properties) the definition of a code is not correct.
Should be &lt;code&gt;,<display&gt;,&lt;codesystem url&gt;

but the codesystem url is an html website of the valueset.

**Comment by pjolo** [comment]
@ralych I have made an export from the vaccination module. In my view, targetDeseases is correctly specified. 
See the picture below:



![image](https://github.com/ehealthsuisse/Impfmodul-Phase-I/assets/87263053/5b3405b1-6498-4bed-92d7-2dc5b2d6ef78)

Can you tell us what exactly is wrong?

**Comment by ch-fuchs** [comment]
Wurde mit der neuen Version 1.3 behoben.
Als System  URL wird nun überall [Sno](http://snomed.info/sct) hinterlegt, siehe https://github.com/ehealthsuisse/Impfmodul-Phase-I/blob/main/Implementation/vaccination-module-backend/config/valuelists/immunizationTargetDesease.properties
