### ISSUE TITLE
Incorrect system url in vaccines-to-targetdiseases.yml

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/Impfmodul-Phase-I#23]
In the config file [vaccines-to-targetdiseases.yml](Implementation/vaccination-module-backend/config/valuelists/vaccines-to-targetdiseases.yml) the 
`targetDiseaseSystem: http://fhir.ch/ig/ch-vacd/ConceptMap-ch-vacd-vaccines-targetdiseases-cm.html`
is not correct. should point to the code system.

**Comment by ch-fuchs** [comment]
Wurde mit der neuen Version 1.3 behoben.
