### ISSUE TITLE
projecthusky dependency issue

### ISSUE THREAD

**Issue by xdubois** [ehealthsuisse/Impfmodul-Phase-I#3]
Hello,

When running the mvn install command on a fresh copy there is a dependency error on the projecthusky* libs

`git clone git@github.com:ehealthsuisse/Impfmodul-Phase-I.git`
`cd Impfmodul-Phase-I/Implementation/vaccination-module-backend`
`mvn clean install`

> Could not resolve dependencies for project ch.admin.bag.vaccination:vaccination-module-backend:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: org.projecthusky.communication:husky-communication-gen:jar:2.0.0, org.projecthusky.fhir.structures:husky-fhir-structures-gen:jar:2.0.0, org.projecthusky.common:husky-common-gen:jar:2.0.0, org.projecthusky.communication:husky-xua-gen-impl:jar:2.0.0, org.projecthusky.communication:husky-xua-gen-api:jar:2.0.0, org.projecthusky.common:husky-common-ch:jar:2.0.0: Could not find artifact org.projecthusky.communication:husky-communication-gen:jar:2.0.0 in local-maven-repo (file:/dev/Impfmodul-Phase-I/Implementation/vaccination-module-backend/lib/local-maven-repo)

Is there any extra configuration steps needed ?

**Comment by ch-fuchs** [comment]
Hello xdubois,

thanks for pointing it out. It seems, gitignore was set up to not to upload jars. This is usually a good thing, however it prevented that the precompiled husky dependent jar libraries were uploaded. 

I have pushed the missing jars now so you can make a fresh pull and rebuild it. 

Let us know if you encounter any other issues.
