### ISSUE TITLE
Incorrect system url in allergyCategory.properties 

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/Impfmodul-Phase-I#6]
In the config file [allergyCategory.properties](https://github.com/ehealthsuisse/Impfmodul-Phase-I/blob/main/Implementation/vaccination-module-backend/config/valuelists/allergyCategory.properties) the definition of a code is not correct.
Should be &lt;code&gt;,<display&gt;,&lt;codesystem url&gt;

but the codesystem url is an html website of the valueset.

**Comment by ch-fuchs** [comment]
Value list has been updated to correspond to the system url
http://hl7.org/fhir/allergy-intolerance-category
as described in
http://hl7.org/fhir/R5/valueset-allergy-intolerance-category.html
