### ISSUE TITLE
Incorrect system url in allergyCode.properties

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/Impfmodul-Phase-I#9]
In the config file [allergyCode.properties](Implementation/vaccination-module-backend/config/valuelists/allergyCode.properties) the definition of a code is not correct.
Should be &lt;code&gt;,<display&gt;,&lt;codesystem url&gt;

but the codesystem url is an html website of the valueset.

**Comment by pjolo** [comment]
@ralych I have made an export from the vaccination module. In my view, targetDeseases is correctly specified. 
See the picture below:

![image](https://github.com/ehealthsuisse/Impfmodul-Phase-I/assets/87263053/15387c7f-2725-4bb2-81ee-1fdcbed3f459)

Can you tell us what exactly is wrong?

**Comment by ch-fuchs** [comment]
Value list has been updated to correspond to the system url
http://snomed.info/sct
as described in
http://fhir.ch/ig/ch-vacd/ValueSet-ch-vacd-immunization-allergyintolerances-vs.html
